## Content Based Recommender System

In [1]:
#1: import data 
#2: Data Preprocessing
#3: Train model
#4: Website
#4: Deploy

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [3]:
anime = pd.read_csv(
    "popular_anime.csv")

In [4]:
anime.head(2)

,id,name,genres,type,episodes,status,aired_from,aired_to,duration_per_ep,score,scored_by,rank,rating,studios,producers,image,trailer,synopsis
0,52991,Frieren: Beyond Journey's End,"Adventure, Drama, Fantasy",TV,28.0,Finished Airing,2023-09-29T00:00:00+00:00,2024-03-22T00:00:00+00:00,24 min per ep,9.3,676737.0,1.0,PG-13 - Teens 13 or older,Madhouse,"Aniplex, Dentsu, Shogakukan-Shueisha Productio...",https://cdn.myanimelist.net/images/anime/1015/...,https://www.youtube.com/watch?v=ZEkwCGJ3o7M,During their decade-long quest to defeat the D...
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy",TV,64.0,Finished Airing,2009-04-05T00:00:00+00:00,2010-07-04T00:00:00+00:00,24 min per ep,9.1,2223666.0,2.0,R - 17+ (violence & profanity),Bones,"Aniplex, Square Enix, Mainichi Broadcasting Sy...",https://cdn.myanimelist.net/images/anime/1208/...,https://www.youtube.com/watch?v=1ac3_YdSSy0,After a horrific alchemy experiment goes wrong...

In [5]:
anime.drop(columns = ['status',"aired_from","aired_to","scored_by","rank","score","image","trailer","producers","duration_per_ep","episodes"],inplace = True)

In [6]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28825 entries, 0 to 28824
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        28825 non-null  int64
 1   name      28825 non-null  object
 2   genres    22756 non-null  object
 3   type      28738 non-null  object
 4   rating    28101 non-null  object
 5   studios   16936 non-null  object
 6   synopsis  23457 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.5+ MB

In [7]:
anime.isnull().sum()

id              0
name            0
genres       6069
type           87
rating        724
studios     11889
synopsis     5368
dtype: int64

In [8]:
# removed null values
anime.dropna(inplace=True)

In [9]:
anime.duplicated().sum()

np.int64(77)

In [10]:
# reomove duplicate values
anime.drop_duplicates(inplace=True)

In [11]:
anime['genres'] = anime['genres'].astype(str).str.strip('[]').str.replace(',,', ',').str.split(',')

In [12]:
anime["genres"]

0                 [Adventure,  Drama,  Fantasy]
1        [Action,  Adventure,  Drama,  Fantasy]
2                   [Drama,  Sci-Fi,  Suspense]
3                   [Action,  Drama,  Suspense]
4                    [Action,  Comedy,  Sci-Fi]
                          ...
28797              [Comedy,  Fantasy,  Mystery]
28798                        [Comedy,  Fantasy]
28801                                  [Comedy]
28806                        [Comedy,  Fantasy]
28821     [Drama,  Fantasy,  Mystery,  Romance]
Name: genres, Length: 14058, dtype: object

In [13]:
# string to list conversion
anime['type'] = anime['type'].apply(lambda x:x.split())
anime['rating'] = anime['rating'].apply(lambda x:x.split())
anime['studios'] = anime['studios'].apply(lambda x:x.split())
anime['synopsis'] = anime['synopsis'].apply(lambda x:x.split())

In [14]:
anime.head()

,id,name,genres,type,rating,studios,synopsis
0,52991,Frieren: Beyond Journey's End,"[Adventure, Drama, Fantasy]",[TV],"[PG-13, -, Teens, 13, or, older]",[Madhouse],"[During, their, decade-long, quest, to, defeat..."
1,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy]",[TV],"[R, -, 17+, (violence, &, profanity)]",[Bones],"[After, a, horrific, alchemy, experiment, goes..."
2,9253,Steins;Gate,"[Drama, Sci-Fi, Suspense]",[TV],"[PG-13, -, Teens, 13, or, older]","[White, Fox]","[Eccentric, scientist, Rintarou, Okabe, has, a..."
3,38524,Attack on Titan Season 3 Part 2,"[Action, Drama, Suspense]",[TV],"[R, -, 17+, (violence, &, profanity)]","[Wit, Studio]","[Seeking, to, restore, humanity's, diminishing..."
4,28977,Gintama Season 4,"[Action, Comedy, Sci-Fi]",[TV],"[PG-13, -, Teens, 13, or, older]","[Bandai, Namco, Pictures]","[Gintoki,, Shinpachi,, and, Kagura, return, as..."

In [15]:
anime['genres'] = anime['genres'].apply(lambda x:[i.replace(" ","")for i in x])
anime['type'] = anime['type'].apply(lambda x:[i.replace(" ","")for i in x])
anime['rating'] = anime['rating'].apply(lambda x:[i.replace(" ","")for i in x])
anime['studios'] = anime['studios'].apply(lambda x:[i.replace(" ","")for i in x])

In [16]:
anime.head()

,id,name,genres,type,rating,studios,synopsis
0,52991,Frieren: Beyond Journey's End,"[Adventure, Drama, Fantasy]",[TV],"[PG-13, -, Teens, 13, or, older]",[Madhouse],"[During, their, decade-long, quest, to, defeat..."
1,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy]",[TV],"[R, -, 17+, (violence, &, profanity)]",[Bones],"[After, a, horrific, alchemy, experiment, goes..."
2,9253,Steins;Gate,"[Drama, Sci-Fi, Suspense]",[TV],"[PG-13, -, Teens, 13, or, older]","[White, Fox]","[Eccentric, scientist, Rintarou, Okabe, has, a..."
3,38524,Attack on Titan Season 3 Part 2,"[Action, Drama, Suspense]",[TV],"[R, -, 17+, (violence, &, profanity)]","[Wit, Studio]","[Seeking, to, restore, humanity's, diminishing..."
4,28977,Gintama Season 4,"[Action, Comedy, Sci-Fi]",[TV],"[PG-13, -, Teens, 13, or, older]","[Bandai, Namco, Pictures]","[Gintoki,, Shinpachi,, and, Kagura, return, as..."

In [17]:
anime['tags'] = anime['genres'] + anime['type'] + anime['rating'] + anime['studios'] + anime['synopsis']

In [18]:
anime.head()

,id,name,genres,type,rating,studios,synopsis,tags
0,52991,Frieren: Beyond Journey's End,"[Adventure, Drama, Fantasy]",[TV],"[PG-13, -, Teens, 13, or, older]",[Madhouse],"[During, their, decade-long, quest, to, defeat...","[Adventure, Drama, Fantasy, TV, PG-13, -, Teen..."
1,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy]",[TV],"[R, -, 17+, (violence, &, profanity)]",[Bones],"[After, a, horrific, alchemy, experiment, goes...","[Action, Adventure, Drama, Fantasy, TV, R, -, ..."
2,9253,Steins;Gate,"[Drama, Sci-Fi, Suspense]",[TV],"[PG-13, -, Teens, 13, or, older]","[White, Fox]","[Eccentric, scientist, Rintarou, Okabe, has, a...","[Drama, Sci-Fi, Suspense, TV, PG-13, -, Teens,..."
3,38524,Attack on Titan Season 3 Part 2,"[Action, Drama, Suspense]",[TV],"[R, -, 17+, (violence, &, profanity)]","[Wit, Studio]","[Seeking, to, restore, humanity's, diminishing...","[Action, Drama, Suspense, TV, R, -, 17+, (viol..."
4,28977,Gintama Season 4,"[Action, Comedy, Sci-Fi]",[TV],"[PG-13, -, Teens, 13, or, older]","[Bandai, Namco, Pictures]","[Gintoki,, Shinpachi,, and, Kagura, return, as...","[Action, Comedy, Sci-Fi, TV, PG-13, -, Teens, ..."

In [19]:
new_df = anime[['id','name','tags']]

In [20]:
# list to string conversion
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [21]:
new_df['tags'][1]

'Action Adventure Drama Fantasy TV R - 17+ (violence & profanity) Bones After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality. Ignoring the alchemical principle banning human transmutation, the boys attempted to bring their recently deceased mother back to life. Instead, they suffered brutal personal loss: Alphonse\'s body disintegrated while Edward lost a leg and then sacrificed an arm to keep Alphonse\'s soul in the physical realm by binding it to a hulking suit of armor. The brothers are rescued by their neighbor Pinako Rockbell and her granddaughter Winry. Known as a bio-mechanical engineering prodigy, Winry creates prosthetic limbs for Edward by utilizing "automail," a tough, versatile metal used in robots and combat armor. After years of training, the Elric brothers set off on a quest to restore their bodies by locating the Philosopher\'s Stone—a powerful gem that allows an alchemist to defy the traditional laws of Equivalent Exchange. As Edward becomes an infamous alchemist and gains the nickname "Fullmetal," the boys\' journey embroils them in a growing conspiracy that threatens the fate of the world.'

In [22]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [23]:
new_df.head()

,id,name,tags
0,52991,Frieren: Beyond Journey's End,adventure drama fantasy tv pg-13 - teens 13 or...
1,5114,Fullmetal Alchemist: Brotherhood,action adventure drama fantasy tv r - 17+ (vio...
2,9253,Steins;Gate,drama sci-fi suspense tv pg-13 - teens 13 or o...
3,38524,Attack on Titan Season 3 Part 2,action drama suspense tv r - 17+ (violence & p...
4,28977,Gintama Season 4,action comedy sci-fi tv pg-13 - teens 13 or ol...

## Steming

In [24]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [25]:
def stem(text):
    y =[]

    for i in text.split():
        y.append(ps.stem(i))

    return" ".join(y)

In [26]:
new_df['tags'] = new_df['tags'].apply(stem)

In [27]:
new_df['tags'][0]

'adventur drama fantasi tv pg-13 - teen 13 or older madhous dure their decade-long quest to defeat the demon king, the member of the hero\' party—himmel himself, the priest heiter, the dwarf warrior eisen, and the elven mage frieren—forg bond through adventur and battles, creat unforgett preciou memori for most of them. however, the time that frieren spend with her comrad is equival to mere a fraction of her life, which ha last over a thousand years. when the parti disband after their victory, frieren casual return to her "usual" routin of collect spell across the continent. due to her differ sens of time, she seemingli hold no strong feel toward the experi she went through. as the year pass, frieren gradual realiz how her day in the hero\' parti truli impact her. wit the death of two of her former companions, frieren begin to regret have taken their presenc for granted; she vow to better understand human and creat real person connections. although the stori of that onc memor journey ha long ended, a new tale is about to begin.'

In [28]:
new_df['tags'][1]

'action adventur drama fantasi tv r - 17+ (violenc & profanity) bone after a horrif alchemi experi goe wrong in the elric household, brother edward and alphons are left in a catastroph new reality. ignor the alchem principl ban human transmutation, the boy attempt to bring their recent deceas mother back to life. instead, they suffer brutal person loss: alphonse\' bodi disintegr while edward lost a leg and then sacrif an arm to keep alphonse\' soul in the physic realm by bind it to a hulk suit of armor. the brother are rescu by their neighbor pinako rockbel and her granddaught winry. known as a bio-mechan engin prodigy, winri creat prosthet limb for edward by util "automail," a tough, versatil metal use in robot and combat armor. after year of training, the elric brother set off on a quest to restor their bodi by locat the philosopher\' stone—a power gem that allow an alchemist to defi the tradit law of equival exchange. as edward becom an infam alchemist and gain the nicknam "fullmetal," the boys\' journey embroil them in a grow conspiraci that threaten the fate of the world.'

## Vectorization

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,stop_words='english')

In [30]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [31]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [32]:
cv.get_feature_names_out()

array(['000', '10', '100', ..., 'zoid', 'zombi', 'zone'],
      shape=(5000,), dtype=object)

In [33]:
from sklearn.metrics.pairwise import cosine_similarity

In [34]:
# calculating cosine distance between vectors 
similarity = cosine_similarity(vectors)

In [35]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(2992, np.float64(0.3489772473629054)),
 (4913, np.float64(0.33978569616828225)),
 (13090, np.float64(0.33588255306372117)),
 (6200, np.float64(0.3069800647022711)),
 (5763, np.float64(0.30236773884142537))]

In [36]:
def recommend(anime):
    anime_index = new_df[new_df['name'] == anime].index[0]
    distances = similarity[anime_index]
    anime_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in anime_list:
         print(new_df.iloc[i[0]]['name'])
    return

In [37]:
recommend("Naruto")

My Hero Academia: Training of the Dead
My Hero Academia: Rescue! Rescue Training
My Hero Academia: Heroes Rising
My Hero Academia Season 4
How I Attended an All-Guy's Mixer

In [38]:
import pickle

In [39]:
pickle.dump(new_df.to_dict(),open('anime_dict.pkl','wb'))

In [40]:
new_df.to_dict()

{'id': {0: 52991,
  1: 5114,
  2: 9253,
  3: 38524,
  4: 28977,
  5: 60022,
  6: 39486,
  7: 11061,
  8: 9969,
  9: 15417,
  10: 820,
  11: 41467,
  12: 34096,
  13: 43608,
  14: 42938,
  15: 4181,
  16: 918,
  17: 28851,
  18: 2904,
  19: 35180,
  20: 15335,
  21: 19,
  22: 58514,
  23: 37491,
  24: 54492,
  25: 51535,
  26: 35247,
  27: 37987,
  28: 40682,
  29: 32281,
  30: 59571,
  32: 49387,
  33: 36838,
  34: 55255,
  35: 37510,
  36: 31758,
  37: 40028,
  38: 263,
  39: 32935,
  40: 37521,
  41: 199,
  42: 17074,
  43: 48583,
  44: 2921,
  45: 47917,
  46: 51009,
  47: 1,
  48: 55690,
  49: 52198,
  50: 50160,
  51: 21,
  52: 58567,
  55: 24701,
  56: 45649,
  57: 44074,
  58: 48569,
  59: 47778,
  60: 52215,
  61: 39894,
  62: 50172,
  63: 53998,
  64: 33095,
  65: 1575,
  66: 44,
  67: 21939,
  68: 33352,
  69: 245,
  70: 40434,
  71: 57864,
  72: 56784,
  73: 5258,
  74: 431,
  75: 164,
  76: 33050,
  77: 49413,
  78: 457,
  79: 50399,
  80: 58125,
  81: 2001,
  82: 46102,
  83: 23273,
  84: 34599,
  85: 11665,
  86: 45576,
  87: 35760,
  88: 54898,
  89: 40591,
  90: 22135,
  91: 1535,
  92: 28891,
  93: 52742,
  94: 34591,
  95: 42310,
  96: 19647,
  97: 36862,
  98: 41084,
  99: 52701,
  100: 33,
  101: 4565,
  102: 38329,
  103: 7311,
  104: 3786,
  105: 37991,
  106: 28957,
  107: 55823,
  108: 55791,
  109: 52034,
  110: 49701,
  111: 32983,
  112: 31757,
  113: 12355,
  114: 10379,
  115: 16498,
  116: 877,
  117: 32,
  118: 40456,
  119: 28735,
  120: 36098,
  121: 7785,
  122: 437,
  123: 170,
  124: 40776,
  125: 40748,
  126: 53447,
  127: 30484,
  128: 11741,
  129: 25777,
  130: 5300,
  131: 578,
  132: 40417,
  133: 53273,
  134: 21329,
  135: 35843,
  136: 7472,
  137: 12365,
  138: 205,
  139: 57647,
  140: 35839,
  141: 4282,
  142: 801,
  143: 57334,
  144: 38474,
  145: 31933,
  146: 40664,
  147: 11981,
  148: 32182,
  149: 30276,
  150: 44070,
  151: 40834,
  152: 37779,
  153: 12431,
  154: 56538,
  155: 33049,
  156: 30654,
  157: 3297,
  158: 47194,
  159: 10165,
  160: 60544,
  161: 54857,
  162: 38450,
  163: 37208,
  164: 6114,
  165: 44087,
  166: 392,
  167: 50265,
  168: 37379,
  169: 35737,
  170: 31181,
  171: 11577,
  172: 36649,
  173: 44511,
  174: 51039,
  177: 26055,
  178: 37105,
  179: 20583,
  180: 36999,
  181: 49722,
  182: 50330,
  183: 136,
  184: 38000,
  185: 40059,
  186: 55888,
  187: 24687,
  188: 36538,
  189: 42203,
  190: 38889,
  191: 21899,
  192: 467,
  193: 39741,
  194: 45556,
  195: 58222,
  196: 33255,
  197: 34612,
  198: 25781,
  199: 40730,
  200: 2246,
  201: 36885,
  202: 38040,
  203: 53236,
  204: 36275,
  205: 48561,
  206: 30709,
  207: 37999,
  208: 35851,
  209: 4921,
  210: 35557,
  211: 5028,
  213: 56523,
  214: 56524,
  215: 55318,
  216: 55102,
  217: 37515,
  218: 37965,
  219: 46095,
  220: 40787,
  221: 9756,
  222: 49721,
  223: 32366,
  224: 5,
  225: 38475,
  226: 53672,
  227: 5205,
  228: 5941,
  229: 31646,
  230: 11979,
  231: 49310,
  232: 38883,
  233: 14397,
  234: 22789,
  236: 9260,
  237: 6945,
  238: 39808,
  239: 30,
  240: 59636,
  242: 55809,
  243: 53540,
  244: 9617,
  245: 39547,
  246: 49458,
  247: 572,
  248: 2251,
  249: 338,
  250: 185,
  251: 39535,
  252: 37095,
  253: 49926,
  254: 39551,
  255: 37822,
  256: 41025,
  257: 46654,
  258: 50407,
  259: 777,
  260: 54870,
  261: 39587,
  262: 2402,
  263: 31988,
  264: 41457,
  265: 13601,
  266: 10030,
  267: 20651,
  268: 55644,
  269: 10937,
  270: 28701,
  271: 5040,
  272: 5081,
  273: 22535,
  274: 10162,
  276: 42886,
  277: 56752,
  278: 55357,
  279: 51805,
  280: 34534,
  281: 12029,
  283: 7655,
  284: 2559,
  285: 42984,
  286: 34240,
  287: 49571,
  288: 137,
  289: 1210,
  290: 51440,
  291: 17389,
  292: 5341,
  293: 40211,
  294: 4081,
  295: 30230,
  296: 3784,
  297: 6594,
  298: 31043,
  299: 39533,
  300: 10534,
  301: 41487,
  302: 54595,
  303: 10863,
  304: 6675,
  305: 5420,
  306: 24415,
  307: 22507,
  308: 12531,
  309: 1365,
  310: 57,
  311: 9989,
  312: 58572,
  313: 52588,
  314: 11917,
  315: 36371,
  316: 759,
  317: 486,
  318: 9735,
  319: 45,
  320: 1735,
  321: 43325,
  322: 38731,
  323: 19363,
  324: 34798,
  325: 30346,
  326: 25835,
  327: 10087,
  328: 2150,
  329: 43,
  330: 10408,
  331: 38826,
  332: 59228,
  333: 52299,
  334: 32188,
  335: 23327,
  336: 44412,
  337: 3002,
  338: 2685,
  339: 513,
  340: 38691,
  341: 50594,
  342: 57067,
  343: 53111,
  344: 35111,
  345: 37520,
  346: 13125,
  347: 2418,
  348: 44940,
  349: 1698,
  350: 32937,
  351: 48316,
  352: 523,
  353: 329,
  354: 264,
  355: 139,
  356: 57592,
  357: 54959,
  358: 37989,
  359: 10271,
  360: 36990,
  361: 1033,
  362: 31812,
  363: 265,
  364: 34036,
  365: 31240,
  366: 54029,
  367: 52578,
  368: 37055,
  369: 25681,
  370: 28805,
  371: 33051,
  372: 11843,
  373: 37450,
  374: 47794,
  375: 512,
  376: 49918,
  377: 45577,
  378: 35838,
  379: 51179,
  380: 35677,
  381: 15227,
  382: 5690,
  383: 40784,
  384: 11977,
  385: 585,
  386: 440,
  387: 50602,
  388: 39247,
  389: 6,
  390: 57181,
  391: 55866,
  392: 53393,
  393: 52684,
  394: 12115,
  395: 2966,
  396: 35466,
  397: 38680,
  398: 1842,
  399: 16664,
  400: 372,
  401: 37078,
  402: 38003,
  403: 5460,
  404: 38249,
  405: 23847,
  406: 6811,
  407: 16894,
  408: 3091,
  409: 627,
  410: 40052,
  411: 813,
  412: 9863,
  413: 18115,
  414: 44055,
  415: 59150,
  417: 59833,
  419: 53127,
  420: 35110,
  421: 18617,
  422: 37171,
  423: 40435,
  424: 40853,
  425: 1453,
  426: 19123,
  427: 32843,
  428: 36946,
  429: 38234,
  430: 42897,
  431: 49114,
  432: 36370,
  433: 10800,
  434: 7791,
  435: 22297,
  436: 37514,
  437: 32005,
  438: 40729,
  439: 3226,
  440: 6864,
  441: 1142,
  442: 49574,
  443: 49596,
  444: 558,
  445: 49590,
  446: 186,
  447: 138,
  448: 23623,
  449: 51019,
  450: 235,
  451: 34636,
  452: 232,
  453: 55655,
  454: 34537,
  455: 32867,
  456: 33674,
  458: 33323,
  459: 4107,
  460: 18195,
  461: 7674,
  462: 38088,
  463: 1519,
  464: 40911,
  465: 42894,
  466: 18,
  467: 59841,
  468: 50250,
  469: 962,
  470: 853,
  471: 1889,
  472: 49052,
  473: 49909,
  474: 47,
  475: 54856,
  476: 44042,
  477: 1430,
  478: 25537,
  479: 48549,
  480: 49521,
  481: 40852,
  482: 50709,
  483: 48736,
  484: 38481,
  485: 28675,
  486: 3371,
  487: 3701,
  488: 30503,
  489: 721,
  490: 50612,
  491: 34572,
  492: 37430,
  493: 56738,
  494: 51335,
  495: 9890,
  496: 31715,
  497: 37962,
  498: 39592,
  499: 39792,
  500: 4477,
  501: 16662,
  502: 41361,
  503: 731,
  504: 28223,
  505: 11597,
  506: 50325,
  507: 49053,
  508: 57524,
  509: 55911,
  510: 53888,
  511: 25313,
  512: 36296,
  513: 35857,
  514: 14713,
  515: 40421,
  516: 1827,
  517: 1604,
  518: 50416,
  519: 50528,
  520: 28171,
  521: 60048,
  522: 53411,
  523: 29831,
  524: 15323,
  525: 10153,
  526: 20899,
  527: 6467,
  528: 40542,
  529: 8129,
  530: 21469,
  531: 18689,
  532: 15059,
  533: 12859,
  534: 50380,
  535: 239,
  536: 121,
  537: 1364,
  538: 51122,
  539: 52826,
  540: 52347,
  541: 32122,
  542: 9130,
  543: 30370,
  544: 1566,
  545: 2581,
  546: 35608,
  547: 59306,
  549: 55701,
  550: 30364,
  551: 6746,
  552: 16918,
  553: 31051,
  554: 6336,
  555: 1382,
  556: 3702,
  557: 32902,
  558: 46569,
  559: 49709,
  560: 339,
  561: 302,
  562: 30831,
  563: 2236,
  564: 60557,
  565: 56653,
  566: 54650,
  567: 17739,
  568: 29755,
  569: 40815,
  571: 3016,
  572: 42941,
  573: 23283,
  574: 4938,
  575: 3901,
  576: 2951,
  577: 50796,
  578: 12069,
  579: 48661,
  580: 51096,
  581: 28025,
  582: 54789,
  583: 18661,
  584: 36369,
  585: 31658,
  586: 40080,
  587: 4722,
  588: 3927,
  589: 42429,
  590: 39198,
  591: 48895,
  592: 10643,
  593: 34076,
  594: 1471,
  595: 135,
  596: 24833,
  597: 53887,
  598: 31251,
  599: 33486,
  600: 3665,
  601: 66,
  602: 22145,
  603: 2449,
  604: 50587,
  605: 32282,
  606: 56980,
  607: 51367,
  608: 13759,
  609: 31149,
  610: 21419,
  611: 6547,
  612: 35062,
  613: 11771,
  614: 27833,
  615: 4155,
  616: 12189,
  617: 4224,
  618: 24277,
  619: 44218,
  620: 1486,
  621: 1367,
  622: 1257,
  623: 851,
  624: 19815,
  625: 49320,
  626: 237,
  627: 38668,
  628: 56063,
  630: 21557,
  631: 23317,
  632: 8425,
  633: 1943,
  634: 40907,
  635: 1559,
  636: 268,
  637: 227,
  638: 2025,
  639: 59953,
  640: 51836,
  641: 25013,
  642: 27821,
  643: 2034,
  644: 1974,
  645: 1506,
  646: 4918,
  647: 18679,
  648: 889,
  649: 781,
  650: 34822,
  651: 59145,
  652: 54791,
  653: 53410,
  654: 52107,
  655: 27989,
  656: 72,
  657: 38993,
  658: 33161,
  659: 4901,
  660: 9204,
  661: 42640,
  662: 2164,
  663: 44931,
  664: 1363,
  665: 49430,
  666: 589,
  667: 41402,
  668: 6045,
  669: 3783,
  671: 44235,
  672: 5681,
  673: 39783,
  674: 1096,
  675: 14513,
  676: 49587,
  677: 535,
  678: 49782,
  679: 34626,
  680: 153,
  681: 20,
  682: 59226,
  683: 9963,
  684: 81,
  685: 27663,
  686: 6421,
  687: 6211,
  688: 2759,
  689: 1914,
  690: 5365,
  691: 42923,
  692: 1482,
  693: 16049,
  694: 50631,
  695: 14813,
  697: 82,
  698: 6171,
  699: 36456,
  700: 40174,
  701: 2167,
  702: 48585,
  703: 7054,
  704: 35382,
  705: 16706,
  706: 14807,
  707: 42250,
  708: 2004,
  709: 4789,
  710: 1065,
  711: 1023,
  712: 3167,
  713: 2563,
  714: 387,
  715: 223,
  716: 9656,
  717: 35788,
  718: 16,
  720: 57616,
  721: 34440,
  722: 39468,
  723: 23199,
  724: 41611,
  725: 40716,
  726: 31173,
  727: 36963,
  728: 861,
  729: 846,
  730: 2448,
  731: 269,
  732: 59497,
  735: 42166,
  737: 34376,
  738: 27831,
  739: 30015,
  740: 32615,
  741: 4672,
  742: 967,
  743: 543,
  744: 416,
  745: 401,
  747: 54915,
  748: 51318,
  749: 51180,
  750: 7720,
  751: 25879,
  752: 77,
  753: 40397,
  755: 38422,
  756: 2890,
  757: 42916,
  758: 7465,
  759: 48411,
  760: 996,
  761: 50346,
  762: 61595,
  765: 52865,
  766: 7222,
  767: 48755,
  768: 38349,
  769: 16067,
  770: 5678,
  771: 5029,
  772: 33221,
  773: 31973,
  774: 39570,
  775: 41923,
  776: 17549,
  777: 1530,
  778: 4772,
  779: 4053,
  780: 20507,
  781: 2154,
  782: 2076,
  783: 38084,
  784: 50593,
  785: 37150,
  786: 60108,
  789: 58883,
  790: 11239,
  791: 12477,
  792: 36702,
  793: 2618,
  794: 38080,
  795: 46422,
  796: 1089,
  797: 793,
  799: 122,
  800: 39565,
  801: 36949,
  802: 58509,
  803: 56785,
  804: 56609,
  805: 55310,
  806: 31174,
  807: 8740,
  808: 5682,
  809: 4059,
  810: 10049,
  811: 35790,
  812: 10721,
  813: 33206,
  814: 34100,
  815: 38337,
  816: 41169,
  817: 18179,
  818: 658,
  819: 11113,
  820: 50207,
  821: 15689,
  822: 35968,
  823: 24997,
  824: 11739,
  825: 21855,
  826: 37675,
  827: 34944,
  828: 27775,
  829: 30279,
  830: 2761,
  831: 21647,
  833: 48171,
  834: 16001,
  835: 2450,
  836: 73,
  837: 187,
  838: 1470,
  839: 38409,
  840: 28,
  841: 15,
  842: 37932,
  843: 57066,
  844: 55742,
  845: 53199,
  846: 52976,
  847: 51818,
  848: 16395,
  849: 7062,
  850: 34437,
  851: 35222,
  852: 17265,
  853: 6774,
  854: 427,
  855: 2829,
  856: 7711,
  857: 6438,
  858: 22961,
  859: 1695,
  860: 4106,
  861: 790,
  862: 7338,
  863: 532,
  864: 32995,
  865: 48580,
  866: 29803,
  867: 59828,
  869: 56215,
  870: 53924,
  871: 9289,
  872: 85,
  874: 3907,
  875: 20057,
  876: 3228,
  877: 27947,
  878: 18397,
  879: 35848,
  880: 28297,
  881: 2952,
  882: 12815,
  883: 14075,
  887: 53287,
  888: 34438,
  889: 13331,
  890: 37786,
  891: 36028,
  892: 38436,
  893: 3572,
  894: 31098,
  896: 29893,
  897: 36563,
  898: 2828,
  899: 38201,
  900: 1088,
  901: 780,
  902: 114,
  903: 24,
  904: 12031,
  905: 31339,
  906: 58059,
  907: 55153,
  908: 52168,
  910: 10012,
  911: 26213,
  912: 31490,
  913: 12113,
  914: 32547,
  915: 35075,
  917: 2159,
  918: 11813,
  919: 1594,
  920: 957,
  921: 934,
  922: 2752,
  923: 14353,
  924: 2471,
  925: 14719,
  926: 322,
  927: 249,
  928: 995,
  929: 59001,
  931: 55855,
  932: 54790,
  933: 51680,
  934: 25517,
  935: 38770,
  936: 16782,
  937: 6007,
  938: 33926,
  939: 5680,
  940: 4985,
  941: 10080,
  942: 34021,
  943: 7645,
  944: 6377,
  945: 37936,
  946: 47405,
  947: 3014,
  948: 795,
  949: 779,
  950: 49469,
  951: 49570,
  952: 50634,
  953: 42249,
  954: 38408,
  955: 2924,
  956: 54764,
  957: 54846,
  958: 54829,
  959: 37029,
  960: 36215,
  961: 35798,
  962: 30415,
  963: 9734,
  964: 18429,
  965: 6862,
  966: 35082,
  967: 2605,
  968: 2158,
  969: 23225,
  970: 41389,
  971: 49828,
  972: 949,
  973: 3588,
  974: 50403,
  975: 42745,
  976: 22,
  977: 60541,
  978: 56704,
  979: 54968,
  980: 52505,
  981: 30885,
  982: 26123,
  983: 8408,
  984: 39392,
  985: 37435,
  986: 8063,
  987: 24471,
  988: 6586,
  989: 569,
  990: 49889,
  991: 9513,
  992: 429,
  993: 31964,
  994: 1921,
  995: 283,
  996: 35507,
  997: 50739,
  999: 25161,
  1000: 55993,
  1001: 52093,
  1002: 36593,
  1003: 14175,
  1004: 36796,
  1005: 32871,
  1006: 36106,
  1007: 40956,
  1008: 3604,
  1009: 6582,
  1011: 32380,
  1012: 20371,
  1013: 1376,
  1014: 31741,
  1015: 4087,
  1016: 48849,
  1017: 890,
  1018: 15039,
  1019: 400,
  1020: 40262,
  1021: 9941,
  1022: 60420,
  1023: 54918,
  1024: 53859,
  1025: 53013,
  1027: 51716,
  1028: 34504,
  1030: 23289,
  1031: 40046,
  1032: 1485,
  1033: 39534,
  1034: 17909,
  1035: 40615,
  1036: 849,
  1037: 49363,
  1038: 48830,
  1039: 48548,
  1040: 49784,
  1041: 12893,
  1042: 37765,
  ...},
 'name': {0: "Frieren: Beyond Journey's End",
  1: 'Fullmetal Alchemist: Brotherhood',
  2: 'Steins;Gate',
  3: 'Attack on Titan Season 3 Part 2',
  4: 'Gintama Season 4',
  5: 'One Piece Fan Letter',
  6: 'Gintama: The Very Final',
  7: 'Hunter x Hunter',
  8: 'Gintama Season 2',
  9: 'Gintama: Enchousen',
  10: 'Legend of the Galactic Heroes',
  11: 'Bleach: Thousand-Year Blood War',
  12: 'Gintama Season 5',
  13: 'Kaguya-sama: Love is War -Ultra Romantic-',
  14: 'Fruits Basket: The Final Season',
  15: 'Clannad: After Story',
  16: 'Gintama',
  17: 'A Silent Voice',
  18: 'Code Geass: Lelouch of the Rebellion R2',
  19: 'March Comes In Like a Lion 2nd Season',
  20: 'Gintama: The Movie: The Final Chapter: Be Forever Yorozuya',
  21: 'Monster',
  22: 'The Apothecary Diaries Season 2',
  23: 'Gintama. Silver Soul Arc - Second Half War',
  24: 'The Apothecary Diaries',
  25: 'Attack on Titan: Final Season - The Final Chapters',
  26: 'Owarimonogatari Second Season',
  27: 'Violet Evergarden: The Movie',
  28: 'Kingdom: Season 3',
  29: 'Your Name.',
  30: 'Attack on Titan: The Last Attack',
  32: 'Vinland Saga Season 2',
  33: 'Gintama. Silver Soul Arc',
  34: 'Alien Stage',
  35: 'Mob Psycho 100 II',
  36: 'Kizumonogatari Part 3: Cold-Blooded',
  37: 'Attack on Titan: Final Season',
  38: 'Fighting Spirit',
  39: 'Haikyu!! 3rd Season',
  40: 'Vinland Saga',
  41: 'Spirited Away',
  42: 'Monogatari Series: Second Season',
  43: 'Attack on Titan: Final Season Part 2',
  44: "Tomorrow's Joe 2",
  45: 'Bocchi the Rock!',
  46: 'Jujutsu Kaisen Season 2',
  47: 'Cowboy Bebop',
  48: 'The Dangers in My Heart Season 2',
  49: 'Kaguya-sama: Love is War -The First Kiss That Never Ends-',
  50: 'Kingdom: Season 4',
  51: 'One Piece',
  52: 'Solo Leveling Season 2: Arise from the Shadow',
  55: 'Mushi-shi: Next Passage Part 2',
  56: 'The First Slam Dunk',
  57: 'Link Click',
  58: '86 Eighty-Six Part 2',
  59: 'Demon Slayer: Kimetsu no Yaiba Entertainment District Arc',
  60: 'Orb: On the Movements of the Earth',
  61: 'Sound! Euphonium 3',
  62: 'Mob Psycho 100 III',
  63: 'Bleach: Thousand-Year Blood War - The Separation',
  64: 'Descending Stories: Showa Genroku Rakugo Shinju',
  65: 'Code Geass: Lelouch of the Rebellion',
  66: 'Samurai X: Trust and Betrayal',
  67: 'Mushi-shi: Next Passage Part 1',
  68: 'Violet Evergarden',
  69: 'Great Teacher Onizuka',
  70: 'The Master of Diabolism 3',
  71: 'Monogatari Series: Off & Monster Season',
  72: 'Bleach: Thousand-Year Blood War - The Conflict',
  73: 'Fighting Spirit: New Challenger',
  74: "Howl's Moving Castle",
  75: 'Princess Mononoke',
  76: "Fate/stay night: Heaven's Feel - III. Spring Song",
  77: 'Link Click Season 2',
  78: 'Mushi-Shi',
  79: "Heaven Official's Blessing Season 2",
  80: 'Look Back',
  81: 'Gurren Lagann',
  82: 'Odd Taxi',
  83: 'Your Lie in April',
  84: 'Made in Abyss',
  85: "Natsume's Book of Friends Season 4",
  86: 'Mushoku Tensei: Jobless Reincarnation Part 2',
  87: 'Attack on Titan Season 3',
  88: 'Bungo Stray Dogs 5',
  89: 'Kaguya-sama: Love is War?',
  90: 'Ping Pong the Animation',
  91: 'Death Note',
  92: 'Haikyu!! 2nd Season',
  93: 'Haikyu!! Movie: The Dumpster Battle',
  94: "Natsume's Book of Friends Season 6",
  95: 'Cyberpunk: Edgerunners',
  96: 'Fighting Spirit: Rising',
  97: 'Made in Abyss: Dawn of the Deep Soul',
  98: 'Made in Abyss: The Golden City of the Scorching Sun',
  99: 'Delicious in Dungeon',
  100: 'Berserk',
  101: 'Gurren Lagann The Movie: The Lights in the Sky are Stars',
  102: 'Rascal Does Not Dream of a Dreaming Girl',
  103: 'The Disappearance of Haruhi Suzumiya',
  104: 'Evangelion: 3.0+1.0 Thrice Upon a Time',
  105: "JoJo's Bizarre Adventure: Golden Wind",
  106: 'Mushishi Zoku Shou: Suzu no Shizuku',
  107: "Natsume's Book of Friends Season 7",
  108: '[Oshi No Ko] Season 2',
  109: '[Oshi No Ko]',
  110: 'Fights Break Sphere: Three Year Agreement',
  111: "Natsume's Book of Friends Season 5",
  112: 'Kizumonogatari Part 2: Hot-Blooded',
  113: 'Wolf Children',
  114: "Natsume's Book of Friends Season 3",
  115: 'Attack on Titan',
  116: 'Nana',
  117: 'Neon Genesis Evangelion: The End of Evangelion',
  118: 'Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train',
  119: 'Showa Genroku Rakugo Shinju',
  120: 'I Want To Eat Your Pancreas',
  121: 'The Tatami Galaxy',
  122: 'Perfect Blue',
  123: 'Slam Dunk',
  124: 'Haikyu!! To the Top 2nd-cour',
  125: 'Jujutsu Kaisen',
  126: 'To Be Hero X',
  127: 'Steins;Gate 0',
  128: 'Fate/Zero Season 2',
  129: 'Attack on Titan Season 2',
  130: "Natsume's Book of Friends Season 2",
  131: 'Grave of the Fireflies',
  132: 'Fruits Basket 2nd Season',
  133: "JoJo's Bizarre Adventure: Stone Ocean Part 3",
  134: 'Mushi-shi: The Shadow that Devours the Sun',
  135: 'Gintama. Slip Arc',
  136: 'Gintama: The Movie',
  137: 'Bakuman. Season 3',
  138: 'Samurai Champloo',
  139: 'Uma Musume: Pretty Derby - Beginning of a New Era',
  140: 'A Place Further Than The Universe',
  141: 'The Garden of Sinners Chapter 5: Paradox Spiral',
  142: 'Ghost in the Shell: Stand Alone Complex 2nd GIG',
  143: 'Dan Da Dan',
  144: 'Laid-Back Camp Season 2',
  145: "JoJo's Bizarre Adventure: Diamond Is Unbreakable",
  146: 'Revue Starlight: The Movie',
  147: 'Puella Magi Madoka Magica the Movie: Rebellion',
  148: 'Mob Psycho 100',
  149: 'One Punch Man',
  150: "Heaven Official's Blessing Special",
  151: 'Ranking of Kings',
  152: 'The Promised Neverland',
  153: 'Space Brothers',
  154: 'Kimi ni Todoke: From Me to You Season 3',
  155: "Fate/stay night: Heaven's Feel - II. Lost Butterfly",
  156: 'Assassination Classroom Second Season',
  157: 'Aria the Origination',
  158: 'Summer Time Rendering',
  159: 'Nichijou - My Ordinary Life',
  160: 'Ne Zha 2',
  161: 'Re:ZERO -Starting Life in Another World- Season 3',
  162: 'The Master of Diabolism Season 2',
  163: 'The Master of Diabolism',
  164: 'Rainbow',
  165: 'Gintama: The Semi-Final',
  166: 'Yu Yu Hakusho: Ghost Files',
  167: 'Spy x Family',
  168: 'Chihayafuru 3',
  169: 'Pluto',
  170: 'Owarimonogatari',
  171: 'Steins;Gate: The Movie - Load Region of Déjà Vu',
  172: 'Banana Fish',
  173: 'Chainsaw Man',
  174: 'Doupo Cangqiong: Nian Fan',
  177: "JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt",
  178: 'Grand Blue Dreaming',
  179: 'Haikyu!!',
  180: 'Zoku Owarimonogatari',
  181: 'Teasing Master Takagi-san: The Movie',
  182: 'Bungo Stray Dogs 4',
  183: 'Hunter x Hunter',

In [41]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [ ]:
import pickle
from sklearn.metrics.pairwise import cosine_similarity

recommendations = {}

for i in range(len(new_df)):

    distances = cosine_similarity(
        vectors[i].reshape(1,-1),
        vectors
    ).flatten()

    anime_list = sorted(
        list(enumerate(distances)),
        key=lambda x:x[1],
        reverse=True
    )[1:6]

    recommendations[new_df.iloc[i]['name']] = [
        new_df.iloc[j[0]]['name']
        for j in anime_list
    ]

pickle.dump(
    recommendations,
    open("recommendations.pkl","wb")
)

print("Done")